### PR TITLE
Change argument name in corelib.parseNameValueArguments

### PR DESCRIPTION
**Pull request by alec-hoyland**
Fix to #110

### CODE REVIEW

**Comment by alec-hoyland** [comment]
Tested on ` '9.9.0.1592791 (R2020b) Update 5'`

**Comment by sg-s** [comment]
nice, but this function is mostly made irrelevant by the new [arguments](https://www.mathworks.com/help/matlab/ref/arguments.html) keyword

**Comment by sg-s** [comment]
look at [this file](https://github.com/sg-s/stg-embedding/blob/73532208de914646bfb2b300697faf27183af1db/%2Bdisplay/plotTransitionMatrix.m) for an example of how the new keyword allows for a more concise argument parsing interface

**Comment by sg-s** [comment]
your change broke everything on R2019b

**Comment by alec-hoyland** [comment]
I suspected there was a breaking change in r2020 nut I haven't been able to find release notes saying so.

**Comment by sg-s** [comment]
never mind i think i patched it. it returns if there's only one argument

**Comment by alec-hoyland** [comment]
With `arguments` over `parseNameValueArguments` you lose some functionality though. You can't just pass a struct anymore...you have to use name-value args.

**Comment by alec-hoyland** [comment]
There are serious benefits to use `arguments` though, and I think that's the way of the future. As much as anyone can say that MATLAB is the way of the future.

**Pull request merged**
