### PR TITLE
setKeyValue and verb functions

### PR DESCRIPTION
**Pull request by alec-hoyland**

### CODE REVIEW

**Comment by alec-hoyland** [comment]
### setKeyValue
Sets properties of a struct based on key-value arguments

```matlab
foo = struct;
foo.a = 123;
foo.b = 456;
```
```matlab
>> structlib.setKeyValue(foo, 'a', 789);
ans = 

  struct with fields:

    a: 789
    b: 456
```

**Comment by sg-s** [comment]
verb is nice, but setKeyValue is pointless.

can be replaced with:

```
foo = struct;
foo.a = 123;
foo.b = 456;

foo.(key_name) = value;
```

see: https://www.mathworks.com/help/matlab/matlab_prog/generate-field-names-from-variables.html

**Comment by alec-hoyland** [comment]
Right, dynamic properties. In general I agree. I've been using it for parsing options passed to functions, but there might be a better way for that too.

**Comment by sg-s** [comment]
remove that from the PR and i'll merge

**Comment by alec-hoyland** [comment]
Actually, pretty much the same code already exists in this repo
https://github.com/sg-s/srinivas.gs_mtools/blob/master/%2Bcorelib/parseNameValueArguments.m

**Pull request merged**
